### ISSUE TITLE
HdfsNetworkConnectException: Connect to "localhost:8020" failed

### ISSUE THREAD

**Issue by cxxly** [camsas/firmament#46]
I deploy firmament according to "Getting started" tutorial. When I start firmament, I come accross follow errors. I don't familiar with hdfs, so forgive me if I miss some steps.
```
cxxly@ubuntu:~/firmament$ sudo build/src/coordinator --listen_uri tcp:133.133.134.130:9001 --task_lib_dir=$(pwd)/build/src/
2016-06-26 07:06:06.825858, p7895, th139744479869056, ERROR Failed to setup RPC connection to "localhost:8020" caused by:
TcpSocket.cpp: 293: HdfsNetworkConnectException: Connect to "localhost:8020" failed: (errno: 111) Connection refused
	@	Hdfs::Internal::TcpSocketImpl::connect(addrinfo*, char const*, char const*, int)
	@	Hdfs::Internal::TcpSocketImpl::connect(char const*, char const*, int)
	@	Hdfs::Internal::RpcChannelImpl::connect()
	@	Hdfs::Internal::RpcChannelImpl::invokeInternal(std::shared_ptr<Hdfs::Internal::RpcRemoteCall>)
	@	Hdfs::Internal::RpcChannelImpl::invoke(Hdfs::Internal::RpcCall const&)
	@	Hdfs::Internal::NamenodeImpl::invoke(Hdfs::Internal::RpcCall const&)
	@	Hdfs::Internal::NamenodeImpl::getFsStats()
	@	Hdfs::Internal::NamenodeProxy::getFsStats()
	@	Hdfs::Internal::FileSystemImpl::getFsStats()
	@	Hdfs::Internal::FileSystemImpl::connect()
	@	Hdfs::FileSystem::connect(char const*, char const*, char const*)
	@	hdfsBuilderConnect
	@	firmament::store::HdfsDataLocalityManager::HdfsDataLocalityManager(firmament::TraceGenerator*)
	@	firmament::Coordinator::Coordinator()
	@	main
	@	Unknown
	@	Unknown
```

**Comment by ms705** [comment]
Hi @cxxly,

Ah, this happens because Firmament cannot find the HDFS name node (which it uses for data-local scheduling). By default, it assumes that the name node is at `localhost:8020`, and this can be customized via command line flags. In your case, however, you probably want to turn the HDFS integration off.

To work around the immediate issue, you can rebuild and pass `--DHDFS_ENABLE=off` to the `cmake` invocation. In the medium term, we'll push a patch that _(i)_ disables HDFS integration by default, and _(ii)_ fails gracefully when the NameNode cannot be reached.

**Comment by ICGog** [comment]
I've pushed a patch [282024](https://review.gerrithub.io/#/c/282024/) that fixes your issue.

**Comment by ms705** [comment]
I think we should also change the `HdfsDataLocalityManager` to print an error and fail gracefully if the HDFS NameNode cannot be reached, so that one can compile with HDFS support enabled.

I'll take a look.

**Comment by ms705** [comment]
Patch now under review in [282133](https://review.gerrithub.io/#/c/282133/).

**Comment by cxxly** [comment]
Look Good to Me :+1:
