### ISSUE TITLE
Received implausibly large message from tcp error

### ISSUE THREAD

**Issue by wybgithub** [camsas/firmament#62]
When I execute the following command
wyb89@ubuntu:~/soft/firmament-master$ ./build/src/coordinator --listen_uri tcp:localhost:8080 --task_lib_dir=./build/src
and then type in "localhost:8080" in my browser
I get following errors
E0102 03:07:12.235633 32499 coordinator_http_ui.cc:1323] Failed running the coordinator's HTTP UI due to bind: Address already in use
F0102 03:07:37.936508 32502 stream_sockets_channel.h:454] Check failed: msg_size < 1024*1024 (5135603447292250196 vs. 1048576) Received implausibly large message from tcp:127.0.0.1:49682
*** Check failure stack trace: ***
    @     0x7f0a1533fffd  google::LogMessage::Fail()
    @     0x7f0a15341d80  google::LogMessage::SendToLog()
    @     0x7f0a1533fbe3  google::LogMessage::Flush()
    @     0x7f0a1534274e  google::LogMessageFatal::~LogMessageFatal()
    @           0x73e99a  firmament::platform_unix::streamsockets::StreamSocketsChannel<>::RecvASecondStage()
    @           0x73cfc7  boost::asio::detail::read_op<>::operator()()
    @           0x73d9b4  boost::asio::detail::reactive_socket_recv_op<>::do_complete()
    @           0x72cc5d  boost::asio::detail::epoll_reactor::descriptor_state::do_complete()
    @           0x7302cd  boost::asio::io_service::run()
    @     0x7f0a162a45d5  (unknown)
    @     0x7f0a15a346ba  start_thread
    @     0x7f0a145963dd  (unknown)
Aborted (core dumped)

I do not know why. Were my operations wrong? Could you please give me some guidance?

**Comment by ms705** [comment]
Hi @wybgithub,

Sorry for the delay, we must have overlooked this issue.

It looks like you're passing port 8080 as the port for Firmament's internal protobuf RPCs, rather than as `--http_ui_port`. If you try to send an HTTP request to the internal RPC port, Firmament will try to deserialize the request as an RPC and get confused. You should use a separate port (default is 9999) for the internal RPCs (`--listen_uri`) and the web UI (`--http_ui_port`).
